Enforce coverage in gha (#213)
* Enforce coverage in gha

Create a new file `.required-coverage` to hold the required coverage
value. Fail the GHA if coverage requirement is not met after compile.

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>

diff --git a/.github/workflows/python-tests.yml b/.github/workflows/python-tests.yml
--- a/.github/workflows/python-tests.yml
+++ b/.github/workflows/python-tests.yml
@@ -77,7 +77,7 @@ jobs:
 
   coverage-compile:
     name: "coverage compile"
-    needs: "run-tests-and-coverage"
+    needs: ["settings", "run-tests-and-coverage"]
     runs-on: "ubuntu-latest"
     steps:
       - name: "Repo checkout"
@@ -104,11 +104,16 @@ jobs:
       - name: "Compile coverage data"
         run: "uvx nox --session combine"
 
-      - name: "Post summary to step summary."
+      - name: "Post summary to step summary"
         run: |
+          export COVERAGE_REQUIRED=$(<.required-coverage)
           export TOTAL=$(python -c "import json;print(json.load(open('coverage.json'))['totals']['percent_covered_display'])")
           echo "TOTAL=$TOTAL" >> $GITHUB_ENV
+          echo "### Minimum coverage required: ${COVERAGE_REQUIRED}%" >> $GITHUB_STEP_SUMMARY
           echo "### Total coverage: ${TOTAL}%" >> $GITHUB_STEP_SUMMARY
+          if [ ${COVERAGE_REQUIRED} -gt $TOTAL ]; then
+            exit 1
+          fi
 
   linters-and-formatters:
     name: "linters and formatters"
